# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
sudo: required
dist: xenial
cache: packages

python:
  - "3.7"

before_install:
  - sudo apt-get install python3-pip
  - sudo pip3 install virtualenv
  - virtualenv -p python3 pytensor
  - source pytensor/bin/activate
  - pip install numpy tensorflow-cpu==2.2.0
  #- sudo apt-get install -y python3
  #- python -V
  # - sudo add-apt-repository ppa:deadsnakes/ppa
  # - sudo apt-get update
  # - sudo apt install python3.7

  #- pip install --upgrade pip setuptools


# matrix:
#   include:
#     - python: 3.7
#       env:
#         - TOXENV=py37
#         - TF_VERSION=2.1.0
#         - TF_PACKAGE=tensorflow-cpu
#     - python: 3.8
#       env:
#         - TOXENV=py38
#         - TF_VERSION=2.2.0
#         - TF_PACKAGE=tensorflow-cpu
# install:
#   - pip install --upgrade pip setuptools
#   - pip install
#   - pip install -e ".[tests]"


env:
 global:
   - CRAN: http://cran.rstudio.com
   - R_BUILD_ARGS="--no-build-vignettes --no-manual"
   - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
   - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions
#- BIOC_USE_DEVEL="FALSE"  ## Use the current release version

r_packages:
   - testthat
   - reticulate
   - knitr
   - viridis
   - tidyverse
bioc_packages:
   - BiocStyle

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings


notifications:
  email:
    on_failure: change