# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
sudo: required
dist: xenial
cache: packages

r:
  - release

python:
  - "3.7"


env:
 global:
   - CRAN: http://cran.rstudio.com
   - R_BUILD_ARGS="--no-build-vignettes --no-manual"
   - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
   - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions
#- BIOC_USE_DEVEL="FALSE"  ## Use the current release version

r_packages:
   - testthat
   - reticulate
   - knitr
   - viridis
   - tidyverse
bioc_packages:
   - BiocStyle

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings


notifications:
  email:
    on_failure: change